cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    admin:
      email: admin@admin.de
      name: Projektleiter Pascal
      password: $2b$12$2UPNnrukkuUCw/sadtVNwu5FpqsZHxPniRlgft6iribV.PCWpIce2
preauthorized:
  emails:

# hashed pw: admin